// ============================================
// BNDL Data — Bundles, Categories, Translations
// ============================================

const BUNDLES = [
  // CATEGORY 1: CLOTHING BRAND
  { id:'BNDL-CLO-001', sku:'BNDL-CLO-001', name:'Essentials Label Bundle', nameGr:'Essentials Label Πακέτο', category:'clothing', tier:'essentials', price:299, originalPrice:450, savings:151, itemCount:20, items:['10× Blank Tees','5× Caps','5× Tote Bags'], includes:'Logo printing on all items', image:'images/clothing-essentials.png' },
  { id:'BNDL-CLO-002', sku:'BNDL-CLO-002', name:'Classics Label Bundle', nameGr:'Classics Label Πακέτο', category:'clothing', tier:'classics', price:449, originalPrice:650, savings:201, itemCount:35, items:['15× Blank Tees','10× Hoodies','5× Caps','5× Tote Bags'], includes:'Logo printing on all items', image:'images/clothing-classics..png' },
  { id:'BNDL-CLO-003', sku:'BNDL-CLO-003', name:'Advanced Label Bundle', nameGr:'Advanced Label Πακέτο', category:'clothing', tier:'advanced', price:599, originalPrice:850, savings:251, itemCount:55, items:['20× Blank Tees','15× Hoodies','10× Caps','10× Tote Bags','Sticker Sheets'], includes:'Logo printing on all items', image:'images/clothing-advanced.png' },

  // CATEGORY 2: CREATOR
  { id:'BNDL-CRE-001', sku:'BNDL-CRE-001', name:'Creator Essentials Bundle', nameGr:'Creator Essentials Πακέτο', category:'creator', tier:'essentials', price:249, originalPrice:400, savings:151, itemCount:20, items:['10× Tees','5× Sticker Sheets','5× Tote Bags'], includes:'Logo printing on all items', image:'images/creator-essentials.png' },
  { id:'BNDL-CRE-002', sku:'BNDL-CRE-002', name:'Creator Classics Bundle', nameGr:'Creator Classics Πακέτο', category:'creator', tier:'classics', price:399, originalPrice:600, savings:201, itemCount:40, items:['15× Tees','10× Hoodies','10× Sticker Sheets','5× Caps'], includes:'Logo printing on all items', image:'images/creator-classics.png' },
  { id:'BNDL-CRE-003', sku:'BNDL-CRE-003', name:'Creator Advanced Bundle', nameGr:'Creator Advanced Πακέτο', category:'creator', tier:'advanced', price:549, originalPrice:800, savings:251, itemCount:65, items:['20× Tees','15× Hoodies','10× Caps','10× Sticker Sheets','10× Tote Bags'], includes:'Logo printing on all items', image:'images/creator-advanced.png' },

  // CATEGORY 3: SPORTS
  { id:'BNDL-SPO-001', sku:'BNDL-SPO-001', name:'Sports Essentials Bundle', nameGr:'Sports Essentials Πακέτο', category:'sports', tier:'essentials', price:299, originalPrice:450, savings:151, itemCount:30, items:['15× Dri-Fit Tees','10× Shorts','5× Caps'], includes:'Logo printing on all items', image:'images/sports-essentials.png' },
  { id:'BNDL-SPO-002', sku:'BNDL-SPO-002', name:'Sports Classics Bundle', nameGr:'Sports Classics Πακέτο', category:'sports', tier:'classics', price:449, originalPrice:650, savings:201, itemCount:40, items:['20× Dri-Fit Tees','10× Shorts','10× Caps','Wristbands'], includes:'Logo printing on all items', image:'images/sports-classics.png' },
  { id:'BNDL-SPO-003', sku:'BNDL-SPO-003', name:'Sports Advanced Bundle', nameGr:'Sports Advanced Πακέτο', category:'sports', tier:'advanced', price:599, originalPrice:850, savings:251, itemCount:60, items:['25× Dri-Fit Tees','15× Shorts','10× Hoodies','10× Caps','Wristbands'], includes:'Logo printing on all items', image:'images/sports-advanced.png' },

  // CATEGORY 4: UNIVERSITY
  { id:'BNDL-UNI-001', sku:'BNDL-UNI-001', name:'University Essentials Bundle', nameGr:'University Essentials Πακέτο', category:'university', tier:'essentials', price:249, originalPrice:400, savings:151, itemCount:30, items:['15× Tees','10× Tote Bags','5× Caps'], includes:'Logo printing on all items', image:'images/university-essentials.png' },
  { id:'BNDL-UNI-002', sku:'BNDL-UNI-002', name:'University Classics Bundle', nameGr:'University Classics Πακέτο', category:'university', tier:'classics', price:399, originalPrice:600, savings:201, itemCount:50, items:['20× Tees','10× Hoodies','10× Tote Bags','10× Caps'], includes:'Logo printing on all items', image:'images/university-classics.png' },
  { id:'BNDL-UNI-003', sku:'BNDL-UNI-003', name:'University Advanced Bundle', nameGr:'University Advanced Πακέτο', category:'university', tier:'advanced', price:549, originalPrice:800, savings:251, itemCount:70, items:['30× Tees','15× Hoodies','15× Tote Bags','10× Caps','Sticker Sheets'], includes:'Logo printing on all items', image:'images/university-advanced.png' },

  // CATEGORY 5: FITNESS
  { id:'BNDL-FIT-001', sku:'BNDL-FIT-001', name:'Fitness Essentials Bundle', nameGr:'Fitness Essentials Πακέτο', category:'fitness', tier:'essentials', price:299, originalPrice:450, savings:151, itemCount:30, items:['15× Tank Tops','10× Shorts','5× Towels'], includes:'Logo printing on all items', image:'images/fitness-essentials.png' },
  { id:'BNDL-FIT-002', sku:'BNDL-FIT-002', name:'Fitness Classics Bundle', nameGr:'Fitness Classics Πακέτο', category:'fitness', tier:'classics', price:449, originalPrice:650, savings:201, itemCount:45, items:['20× Tank Tops','10× Shorts','10× Hoodies','5× Towels','Wristbands'], includes:'Logo printing on all items', image:'images/fitness-classics.png' },
  { id:'BNDL-FIT-003', sku:'BNDL-FIT-003', name:'Fitness Advanced Bundle', nameGr:'Fitness Advanced Πακέτο', category:'fitness', tier:'advanced', price:599, originalPrice:850, savings:251, itemCount:75, items:['25× Tank Tops','15× Shorts','15× Hoodies','10× Towels','10× Shaker Bottles'], includes:'Logo printing on all items', image:'images/fitness-advanced.png' },

  // CATEGORY 6: CAFE
  { id:'BNDL-CAF-001', sku:'BNDL-CAF-001', name:'Cafe Essentials Bundle', nameGr:'Cafe Essentials Πακέτο', category:'cafe', tier:'essentials', price:249, originalPrice:400, savings:151, itemCount:30, items:['10× Aprons','10× Caps','10× Mugs'], includes:'Logo printing on all items', image:'images/cafe-essentials.png' },
  { id:'BNDL-CAF-002', sku:'BNDL-CAF-002', name:'Cafe Classics Bundle', nameGr:'Cafe Classics Πακέτο', category:'cafe', tier:'classics', price:399, originalPrice:600, savings:201, itemCount:50, items:['15× Aprons','15× Tees','10× Mugs','10× Tote Bags'], includes:'Logo printing on all items', image:'images/cafe-classics.png' },
  { id:'BNDL-CAF-003', sku:'BNDL-CAF-003', name:'Cafe Advanced Bundle', nameGr:'Cafe Advanced Πακέτο', category:'cafe', tier:'advanced', price:549, originalPrice:800, savings:251, itemCount:65, items:['20× Aprons','20× Tees','15× Mugs','10× Tote Bags','Sticker Sheets'], includes:'Logo printing on all items', image:'images/cafe-advanced.png' },

  // CATEGORY 7: MUSIC & EVENTS
  { id:'BNDL-MUS-001', sku:'BNDL-MUS-001', name:'Music Essentials Bundle', nameGr:'Music Essentials Πακέτο', category:'music', tier:'essentials', price:299, originalPrice:450, savings:151, itemCount:40, items:['20× Tees','10× Caps','10× Tote Bags'], includes:'Logo printing on all items', image:'images/music-essentials.png' },
  { id:'BNDL-MUS-002', sku:'BNDL-MUS-002', name:'Music Classics Bundle', nameGr:'Music Classics Πακέτο', category:'music', tier:'classics', price:449, originalPrice:650, savings:201, itemCount:50, items:['30× Tees','10× Hoodies','10× Caps','Wristbands'], includes:'Logo printing on all items', image:'images/music-classics.png' },
  { id:'BNDL-MUS-003', sku:'BNDL-MUS-003', name:'Music Advanced Bundle', nameGr:'Music Advanced Πακέτο', category:'music', tier:'advanced', price:599, originalPrice:850, savings:251, itemCount:65, items:['30× Tees','15× Hoodies','10× Caps','10× Tote Bags','Sticker Sheets','Wristbands'], includes:'Logo printing on all items', image:'images/music-advanced.png' },

  // CATEGORY 8: CORPORATE
  { id:'BNDL-COR-001', sku:'BNDL-COR-001', name:'Corporate Essentials Bundle', nameGr:'Corporate Essentials Πακέτο', category:'corporate', tier:'essentials', price:349, originalPrice:500, savings:151, itemCount:35, items:['15× Polo Shirts','10× Notebooks','10× Pens'], includes:'Logo printing on all items', image:'images/corporate-essentials.png' },
  { id:'BNDL-COR-002', sku:'BNDL-COR-002', name:'Corporate Classics Bundle', nameGr:'Corporate Classics Πακέτο', category:'corporate', tier:'classics', price:499, originalPrice:700, savings:201, itemCount:50, items:['20× Polo Shirts','10× Hoodies','10× Notebooks','10× Mugs'], includes:'Logo printing on all items', image:'images/corporate-classics.png' },
  { id:'BNDL-COR-003', sku:'BNDL-COR-003', name:'Corporate Advanced Bundle', nameGr:'Corporate Advanced Πακέτο', category:'corporate', tier:'advanced', price:649, originalPrice:900, savings:251, itemCount:75, items:['25× Polo Shirts','15× Hoodies','15× Notebooks','10× Mugs','10× USB Drives'], includes:'Logo printing on all items', image:'images/corporate-advanced.png' },

  // CATEGORY 9: ESPORTS
  { id:'BNDL-ESP-001', sku:'BNDL-ESP-001', name:'Esports Essentials Bundle', nameGr:'Esports Essentials Πακέτο', category:'esports', tier:'essentials', price:299, originalPrice:450, savings:151, itemCount:20, items:['10× Gaming Tees','5× Hoodies','5× Mousepads'], includes:'Logo printing on all items', image:'images/esports-essentials.png' },
  { id:'BNDL-ESP-002', sku:'BNDL-ESP-002', name:'Esports Classics Bundle', nameGr:'Esports Classics Πακέτο', category:'esports', tier:'classics', price:449, originalPrice:650, savings:201, itemCount:40, items:['15× Gaming Tees','10× Hoodies','10× Mousepads','5× Caps'], includes:'Logo printing on all items', image:'images/esports-classics.png' },
  { id:'BNDL-ESP-003', sku:'BNDL-ESP-003', name:'Esports Advanced Bundle', nameGr:'Esports Advanced Πακέτο', category:'esports', tier:'advanced', price:599, originalPrice:850, savings:251, itemCount:55, items:['20× Gaming Tees','15× Hoodies','10× Mousepads','10× Caps','Sticker Sheets','Wristbands'], includes:'Logo printing on all items', image:'images/esports-advanced.png' },

  // CATEGORY 10: NIGHTLIFE
  { id:'BNDL-NIG-001', sku:'BNDL-NIG-001', name:'Nightlife Essentials Bundle', nameGr:'Nightlife Essentials Πακέτο', category:'nightlife', tier:'essentials', price:299, originalPrice:450, savings:151, itemCount:35, items:['15× Tees','10× Caps','10× Wristbands'], includes:'Logo printing on all items', image:'images/nightlife-essentials.png' },
  { id:'BNDL-NIG-002', sku:'BNDL-NIG-002', name:'Nightlife Classics Bundle', nameGr:'Nightlife Classics Πακέτο', category:'nightlife', tier:'classics', price:449, originalPrice:650, savings:201, itemCount:40, items:['20× Tees','10× Hoodies','10× Caps','Sticker Sheets','Wristbands'], includes:'Logo printing on all items', image:'images/nightlife-classics.png' },
  { id:'BNDL-NIG-003', sku:'BNDL-NIG-003', name:'Nightlife Advanced Bundle', nameGr:'Nightlife Advanced Πακέτο', category:'nightlife', tier:'advanced', price:599, originalPrice:850, savings:251, itemCount:70, items:['30× Tees','15× Hoodies','15× Caps','10× Tote Bags','Sticker Sheets','Wristbands'], includes:'Logo printing on all items', image:'images/nightlife-advanced.png' },

  // CATEGORY 11: WEDDINGS
  { id:'BNDL-WED-001', sku:'BNDL-WED-001', name:'Wedding Essentials Bundle', nameGr:'Wedding Essentials Πακέτο', category:'weddings', tier:'essentials', price:249, originalPrice:400, savings:151, itemCount:20, items:['10× Tees','5× Tote Bags','5× Caps'], includes:'Logo/design printing on all items', image:'images/weddings-essentials.png' },
  { id:'BNDL-WED-002', sku:'BNDL-WED-002', name:'Wedding Classics Bundle', nameGr:'Wedding Classics Πακέτο', category:'weddings', tier:'classics', price:399, originalPrice:600, savings:201, itemCount:40, items:['15× Tees','10× Hoodies','10× Tote Bags','5× Caps'], includes:'Logo/design printing on all items', image:'images/weddings-classics.png' },
  { id:'BNDL-WED-003', sku:'BNDL-WED-003', name:'Wedding Advanced Bundle', nameGr:'Wedding Advanced Πακέτο', category:'weddings', tier:'advanced', price:549, originalPrice:800, savings:251, itemCount:65, items:['20× Tees','15× Hoodies','10× Robes','10× Tote Bags','10× Caps'], includes:'Logo/design printing on all items', image:'images/weddings-advanced.png' },

  // CATEGORY 12: NONPROFITS
  { id:'BNDL-NON-001', sku:'BNDL-NON-001', name:'Nonprofit Essentials Bundle', nameGr:'Nonprofit Essentials Πακέτο', category:'nonprofits', tier:'essentials', price:199, originalPrice:350, savings:151, itemCount:30, items:['15× Tees','10× Tote Bags','5× Caps'], includes:'Logo printing on all items', image:'images/nonprofits-essentials.png' },
  { id:'BNDL-NON-002', sku:'BNDL-NON-002', name:'Nonprofit Classics Bundle', nameGr:'Nonprofit Classics Πακέτο', category:'nonprofits', tier:'classics', price:349, originalPrice:550, savings:201, itemCount:55, items:['25× Tees','10× Hoodies','10× Tote Bags','10× Caps'], includes:'Logo printing on all items', image:'images/nonprofits-classics.png' },
  { id:'BNDL-NON-003', sku:'BNDL-NON-003', name:'Nonprofit Advanced Bundle', nameGr:'Nonprofit Advanced Πακέτο', category:'nonprofits', tier:'advanced', price:499, originalPrice:750, savings:251, itemCount:70, items:['30× Tees','15× Hoodies','15× Tote Bags','10× Caps','Sticker Sheets'], includes:'Logo printing on all items', image:'images/nonprofits-advanced.png' },

  // CATEGORY 13: CREATIVES
  { id:'BNDL-ART-001', sku:'BNDL-ART-001', name:'Creatives Essentials Bundle', nameGr:'Creatives Essentials Πακέτο', category:'creatives', tier:'essentials', price:249, originalPrice:400, savings:151, itemCount:25, items:['10× Tees','5× Tote Bags','5× Sticker Sheets','5× Notebooks'], includes:'Logo/artwork printing on all items', image:'images/creatives-essentials.png' },
  { id:'BNDL-ART-002', sku:'BNDL-ART-002', name:'Creatives Classics Bundle', nameGr:'Creatives Classics Πακέτο', category:'creatives', tier:'classics', price:399, originalPrice:600, savings:201, itemCount:45, items:['15× Tees','10× Hoodies','10× Tote Bags','10× Sticker Sheets'], includes:'Logo/artwork printing on all items', image:'images/creatives-classics.png' },
  { id:'BNDL-ART-003', sku:'BNDL-ART-003', name:'Creatives Advanced Bundle', nameGr:'Creatives Advanced Πακέτο', category:'creatives', tier:'advanced', price:549, originalPrice:800, savings:251, itemCount:70, items:['20× Tees','15× Hoodies','10× Tote Bags','10× Sticker Sheets','10× Notebooks','5× Caps'], includes:'Logo/artwork printing on all items', image:'images/creatives-advanced.png' },

  // CATEGORY 14: CUSTOM
  { id:'BNDL-CUS-001', sku:'BNDL-CUS-001', name:'Custom Essentials Bundle', nameGr:'Custom Essentials Πακέτο', category:'custom', tier:'essentials', price:299, originalPrice:450, savings:151, itemCount:20, items:['Build your own bundle — choose any 20 items from our catalog'], includes:'Logo printing on all items', image:'images/custom-essentials.png' },
  { id:'BNDL-CUS-002', sku:'BNDL-CUS-002', name:'Custom Classics Bundle', nameGr:'Custom Classics Πακέτο', category:'custom', tier:'classics', price:449, originalPrice:650, savings:201, itemCount:40, items:['Build your own bundle — choose any 40 items from our catalog'], includes:'Logo printing on all items', image:'images/custom-classics.png' },
  { id:'BNDL-CUS-003', sku:'BNDL-CUS-003', name:'Custom Advanced Bundle', nameGr:'Custom Advanced Πακέτο', category:'custom', tier:'advanced', price:599, originalPrice:850, savings:251, itemCount:65, items:['Build your own bundle — choose any 65 items from our catalog'], includes:'Logo printing on all items', image:'images/custom-advanced.png' },
];

const CATEGORIES = [
  { id:'clothing', name:'Clothing Brand', nameGr:'Ρούχα Brand', slug:'clothing', image:'images/clothing-essentials.png' },
  { id:'creator', name:'Creator', nameGr:'Creator', slug:'creator', image:'images/creator-essentials.png' },
  { id:'sports', name:'Sports', nameGr:'Αθλητικά', slug:'sports', image:'images/sports-essentials.png' },
  { id:'university', name:'University', nameGr:'Πανεπιστήμιο', slug:'university', image:'images/university-essentials.png' },
  { id:'fitness', name:'Fitness', nameGr:'Fitness', slug:'fitness', image:'images/fitness-essentials.png' },
  { id:'cafe', name:'Cafe', nameGr:'Καφετέρια', slug:'cafe', image:'images/cafe-essentials.png' },
  { id:'music', name:'Music & Events', nameGr:'Μουσική & Events', slug:'music', image:'images/music-essentials.png' },
  { id:'corporate', name:'Corporate', nameGr:'Εταιρικό', slug:'corporate', image:'images/corporate-essentials.png' },
  { id:'esports', name:'Esports', nameGr:'Esports', slug:'esports', image:'images/esports-essentials.png' },
  { id:'nightlife', name:'Nightlife', nameGr:'Nightlife', slug:'nightlife', image:'images/nightlife-essentials.png' },
  { id:'weddings', name:'Weddings', nameGr:'Γάμοι', slug:'weddings', image:'images/weddings-essentials.png' },
  { id:'nonprofits', name:'Nonprofits', nameGr:'ΜΚΟ', slug:'nonprofits', image:'images/nonprofits-essentials.png' },
  { id:'creatives', name:'Creatives', nameGr:'Δημιουργοί', slug:'creatives', image:'images/creatives-essentials.png' },
  { id:'custom', name:'Custom', nameGr:'Custom', slug:'custom', image:'images/custom-essentials.png' },
];

const TRANSLATIONS = {
  en: {
    nav: { bundles:'Bundles', membership:'Membership', about:'About', faq:'FAQ', contact:'Contact', blog:'Blog', bookCall:'Book a Call', buildOwn:'Build Your Own' },
    hero: { label:'Premium Branded Merchandise', title:'Your Dream, One BNDL', subtitle:'Fixed-price branded merchandise bundles for your business. Choose, customize, and launch your brand.', cta:'Shop Bundles' },
    marquee: 'Premium Quality • Fixed Prices • Custom Branding • Fast Production • Greece Shipping • All Sizes XS–2XL',
    howItWorks: { label:'Simple Process', title:'How It Works', subtitle:'From order to delivery in 4 simple steps', steps:[ { title:'Choose Bundle', desc:'Pick the perfect bundle for your brand and business.' }, { title:'Checkout', desc:'Complete your purchase securely online.' }, { title:'Send Logo', desc:'Send us your logo in high resolution after purchase.' }, { title:'Receive Products', desc:'Get your branded products delivered to your door.' } ] },
    featured: { label:'Best Sellers', title:'Featured Bundles', subtitle:'Our most popular bundles chosen by businesses like yours' },
    categories: { label:'Browse By Industry', title:'Categories', subtitle:'Find the perfect bundle for your niche' },
    testimonials: { label:'What Our Clients Say', title:'Testimonials' },
    trust: { label:'Why Choose BNDL', title:'Built for Your Brand', items:[ { number:'42', suffix:'+', label:'Bundle Options' }, { number:'10', suffix:'-15', label:'Days Production' }, { number:'14', suffix:'', label:'Categories' }, { number:'100', suffix:'%', label:'Custom Branding' } ] },
    newsletter: { title:'Stay in the Loop', subtitle:'Get exclusive offers and new bundle alerts.', placeholder:'Enter your email', cta:'Subscribe' },
    footer: { desc:'Premium branded merchandise bundles for businesses and creators. Fixed prices, custom branding, fast production.', shop:'Shop', company:'Company', support:'Support', rights:'All rights reserved.', powered:'powered by', returns:'Returns Policy', legal:'Legal Terms', 'legal-title':'LEGAL' },
    bundles: { title:'All Bundles', subtitle:'Premium branded merchandise bundles for every industry', filterAll:'All', sortLabel:'Sort by', sortOptions:{ popular:'Most Popular', priceLow:'Price: Low to High', priceHigh:'Price: High to Low' }, search:'Search bundles...', viewBundle:'View Bundle', items:'items', vat:'+24% VAT', was:'was', save:'Save' },
    bundle: { whatsIncluded:"What's Included", howItWorks:'How It Works', addToCart:'Add to Cart', added:'Added!', sizeNote:'After purchase, you\'ll select your size breakdown (XS to 2XL) for each item.', printNote:'Multi-color printing may increase cost. Simple 1-2 color designs are included in the bundle price.', related:'Related Bundles', backToBundles:'← Back to Bundles' },
    cart: { title:'Your Cart', empty:'Your cart is empty', emptyDesc:'Browse our bundles and find the perfect one for your brand.', shopNow:'Shop Bundles', subtotal:'Subtotal', vat:'VAT (24%)', shipping:'Shipping', shippingNote:'Calculated at checkout', total:'Total', checkout:'Proceed to Checkout', remove:'Remove', qty:'Qty', discountLabel:'Discount Code', apply:'Apply', discountApplied:'Discount applied!', invalidCode:'Invalid discount code' },
    checkout: { title:'Checkout', personal:'Personal Information', fullName:'Full Name', email:'Email Address', phone:'Phone Number', company:'Company Name (Optional)', vatNumber:'VAT Number (for invoice)', shippingTitle:'Shipping Address', address:'Street Address', city:'City', postal:'Postal Code', country:'Country', orderSummary:'Order Summary', payNow:'Pay Now', paymentNote:'Payment integration coming soon. We\'ll contact you to arrange payment.', success:'Order Placed!', successMsg:'Thank you for your order. We\'ll send you an email with instructions to submit your logo.' },
    about: { title:'About BNDL', subtitle:'Premium branded merchandise, simplified', story:'BNDL takes the complexity out of branded merchandise. As a sub-brand of Succit — Greece\'s leading wholesale import, production, and customization company — we offer fixed-price bundles that include everything from blank products to custom printing with your logo.', mission:'Our mission is to make branded merchandise accessible to every business, creator, and organization — with transparent pricing, premium quality, and fast turnaround.', valuesTitle:'Our Values', values:[ { title:'Transparency', desc:'Fixed prices, no hidden fees. What you see is what you pay.' }, { title:'Quality', desc:'Premium products from trusted manufacturers across Europe.' }, { title:'Speed', desc:'10-15 business days from logo approval to delivery.' }, { title:'Customization', desc:'Your brand, your way. Full custom printing and embroidery.' } ], storyLabel:'OUR STORY', heroTitle:'WE BUILD BRANDS.', statement:'BNDL IS THE FASTEST WAY TO START YOUR BRAND.', statementDesc:'We started BNDL because launching a brand shouldn\'t require 10 different suppliers, 20 emails and 3 months of waiting. One bundle. Everything you need. Powered by Succit wholesale infrastructure.', stat1:'Bundle Categories', stat2:'Ready-Made Bundles', stat3:'Average Production Start', stat4:'Custom Branded', missionTitle:'OUR MISSION', missionDesc:'Να κάνουμε το custom branding προσιτό και γρήγορο για κάθε επιχείρηση στην Ελλάδα.', succitPretitle:'BNDL IS POWERED BY', succitDesc:'Greece\'s leading wholesale import & customization company', succitButton:'Visit Succit →', ctaTitle:'Ready to build your brand?', ctaPrimary:'Shop Bundles', ctaSecondary:'Book a Call' },
    contact: { title:'Contact Us', subtitle:'Have a question? We\'d love to hear from you.', name:'Your Name', email:'Email Address', subject:'Subject', message:'Your Message', send:'Send Message', info:'Contact Information', emailLabel:'Email', phoneLabel:'Phone', addressLabel:'Address', addressValue:'Athens, Greece' },
    faq: { title:'FAQ', subtitle:'Everything you need to know about ordering with BNDL' },
    bookCall: { title:'Book a Call', subtitle:'Schedule a free consultation to discuss your branded merchandise needs.', desc:'During the call, we\'ll discuss your brand, help you choose the right bundle, and answer any questions about printing, sizing, and delivery.', contact:'Prefer to reach out directly?' },
    buildOwn: { title:'Build Your Own Bundle', subtitle:'Can\'t find the perfect bundle? Tell us what you need.', desc:'Fill out the form below and we\'ll get back to you within 24 hours with a custom quote.', name:'Your Name', email:'Email Address', phone:'Phone Number', company:'Company Name', description:'Describe what you need', quantity:'Estimated Quantity', budget:'Budget Range', submit:'Submit Inquiry', success:'Inquiry sent! We\'ll get back to you within 24 hours.' },
    blog: { title:'Blog', subtitle:'Tips, trends, and insights on branded merchandise', readMore:'Read More', minRead:'min read' },
    membership: { title:'BNDL Membership', subtitle:'Save more with every order', monthly:'MONTHLY', annual:'ANNUAL ★ BEST VALUE', perMonth:'/month', perYear:'/year', savings:'(instead of €228 — save €79)', feature1:'✓ 5% discount on all bundles', feature2:'✓ Free stickers with every order', feature3:'✓ 1 custom pen per order', feature4:'✓ Consulting support (email)', feature5:'✓ Priority production', feature6:'✓ Consulting support (email + phone)', feature7:'✓ 1 free sampling per year', feature8:'✓ Exclusive member offers', getStarted:'Get Started Now', faqTitle:'Frequently Asked Questions', faq1:{ question:'How does the 5% discount work?', answer:'It applies automatically to every bundle order you make while you\'re a member.' }, faq2:{ question:'When am I charged?', answer:'Immediately upon signup and then automatically every month/year.' }, faq3:{ question:'Can I cancel?', answer:'Yes, anytime without cancellation fees.' }, faq4:{ question:'Are the stickers and pen custom?', answer:'The stickers feature your logo. The pen is branded BNDL.' } },
    cookie: { text:'We use cookies to improve your experience. By continuing to browse, you agree to our use of cookies.', accept:'Accept' },
    backToTop: 'Back to top',
  },
  gr: {
    nav: { bundles:'Πακέτα', membership:'Membership', about:'Σχετικά', faq:'FAQ', contact:'Επικοινωνία', blog:'Blog', bookCall:'Κλείσε Ραντεβού', buildOwn:'Φτιάξε το Δικό σου' },
    hero: { label:'Premium Branded Merchandise', title:'Your Dream, One BNDL', subtitle:'Πακέτα branded merchandise σε σταθερές τιμές για την επιχείρησή σου. Διάλεξε, προσάρμοσε και ξεκίνα.', cta:'Δες τα Πακέτα' },
    marquee: 'Premium Ποιότητα • Σταθερές Τιμές • Custom Branding • Γρήγορη Παραγωγή • Αποστολή Ελλάδα • Μεγέθη XS–2XL',
    howItWorks: { label:'Απλή Διαδικασία', title:'Πώς Λειτουργεί', subtitle:'Από την παραγγελία στην παράδοση σε 4 απλά βήματα', steps:[ { title:'Διάλεξε Πακέτο', desc:'Επέλεξε το ιδανικό πακέτο για το brand σου.' }, { title:'Ολοκλήρωσε Αγορά', desc:'Ολοκλήρωσε την αγορά σου online με ασφάλεια.' }, { title:'Στείλε Logo', desc:'Στείλε μας το logo σου σε υψηλή ανάλυση μετά την αγορά.' }, { title:'Παραλαβή', desc:'Παράλαβε τα branded προϊόντα στην πόρτα σου.' } ] },
    featured: { label:'Δημοφιλή', title:'Προτεινόμενα Πακέτα', subtitle:'Τα πιο δημοφιλή πακέτα που επιλέγουν επιχειρήσεις σαν τη δική σου' },
    categories: { label:'Ανά Κλάδο', title:'Κατηγορίες', subtitle:'Βρες το τέλειο πακέτο για τον κλάδο σου' },
    testimonials: { label:'Τι Λένε οι Πελάτες μας', title:'Κριτικές' },
    trust: { label:'Γιατί BNDL', title:'Φτιαγμένο για το Brand σου', items:[ { number:'42', suffix:'+', label:'Επιλογές Πακέτων' }, { number:'10', suffix:'-15', label:'Ημέρες Παραγωγής' }, { number:'14', suffix:'', label:'Κατηγορίες' }, { number:'100', suffix:'%', label:'Custom Branding' } ] },
    newsletter: { title:'Μείνε Ενημερωμένος', subtitle:'Λάβε αποκλειστικές προσφορές και ειδοποιήσεις.', placeholder:'Email σου', cta:'Εγγραφή' },
    footer: { desc:'Premium branded merchandise πακέτα για επιχειρήσεις και creators. Σταθερές τιμές, custom branding, γρήγορη παραγωγή.', shop:'Κατάστημα', company:'Εταιρεία', support:'Υποστήριξη', rights:'Με επιφύλαξη παντός δικαιώματος.', powered:'powered by', returns:'Πολιτική Επιστροφών', legal:'Νομικοί Όροι', 'legal-title':'ΝΟΜΙΚΑ' },
    bundles: { title:'Όλα τα Πακέτα', subtitle:'Premium branded merchandise πακέτα για κάθε κλάδο', filterAll:'Όλα', sortLabel:'Ταξινόμηση', sortOptions:{ popular:'Δημοφιλέστερα', priceLow:'Τιμή: Χαμηλή → Υψηλή', priceHigh:'Τιμή: Υψηλή → Χαμηλή' }, search:'Αναζήτηση πακέτων...', viewBundle:'Δες το Πακέτο', items:'αντικείμενα', vat:'+24% ΦΠΑ', was:'ήταν', save:'Κέρδος' },
    bundle: { whatsIncluded:'Τι Περιλαμβάνει', howItWorks:'Πώς Λειτουργεί', addToCart:'Προσθήκη στο Καλάθι', added:'Προστέθηκε!', sizeNote:'Μετά την αγορά, θα επιλέξεις τα μεγέθη (XS έως 2XL) για κάθε προϊόν.', printNote:'Η πολύχρωμη εκτύπωση μπορεί να αυξήσει το κόστος. Απλά σχέδια 1-2 χρωμάτων περιλαμβάνονται στην τιμή.', related:'Σχετικά Πακέτα', backToBundles:'← Πίσω στα Πακέτα' },
    cart: { title:'Το Καλάθι σου', empty:'Το καλάθι σου είναι άδειο', emptyDesc:'Περιήγησε τα πακέτα μας και βρες το ιδανικό για το brand σου.', shopNow:'Δες τα Πακέτα', subtotal:'Υποσύνολο', vat:'ΦΠΑ (24%)', shipping:'Αποστολή', shippingNote:'Υπολογίζεται στο checkout', total:'Σύνολο', checkout:'Συνέχεια στο Checkout', remove:'Αφαίρεση', qty:'Ποσ.', discountLabel:'Κωδικός Έκπτωσης', apply:'Εφαρμογή', discountApplied:'Η έκπτωση εφαρμόστηκε!', invalidCode:'Μη έγκυρος κωδικός' },
    checkout: { title:'Checkout', personal:'Προσωπικά Στοιχεία', fullName:'Ονοματεπώνυμο', email:'Email', phone:'Τηλέφωνο', company:'Επωνυμία Εταιρείας (Προαιρετικό)', vatNumber:'ΑΦΜ (για τιμολόγιο)', shippingTitle:'Διεύθυνση Αποστολής', address:'Διεύθυνση', city:'Πόλη', postal:'Τ.Κ.', country:'Χώρα', orderSummary:'Σύνοψη Παραγγελίας', payNow:'Πληρωμή', paymentNote:'Η ενσωμάτωση πληρωμών έρχεται σύντομα. Θα επικοινωνήσουμε μαζί σου.', success:'Η Παραγγελία Καταχωρήθηκε!', successMsg:'Ευχαριστούμε. Θα σου στείλουμε email με οδηγίες για το logo σου.' },
    about: { title:'Σχετικά με το BNDL', subtitle:'Premium branded merchandise, απλοποιημένο', story:'Το BNDL αφαιρεί την πολυπλοκότητα από το branded merchandise. Ως sub-brand της Succit — της κορυφαίας εταιρείας χονδρικής εισαγωγής, παραγωγής και customization στην Ελλάδα — προσφέρουμε πακέτα σταθερής τιμής.', mission:'Η αποστολή μας είναι να κάνουμε το branded merchandise προσβάσιμο σε κάθε επιχείρηση, creator και οργανισμό — με διαφανείς τιμές, premium ποιότητα και γρήγορη παράδοση.', valuesTitle:'Οι Αξίες μας', values:[ { title:'Διαφάνεια', desc:'Σταθερές τιμές, χωρίς κρυφές χρεώσεις.' }, { title:'Ποιότητα', desc:'Premium προϊόντα από αξιόπιστους κατασκευαστές.' }, { title:'Ταχύτητα', desc:'10-15 εργάσιμες ημέρες από την έγκριση logo.' }, { title:'Προσαρμογή', desc:'Το brand σου, με τον τρόπο σου. Custom εκτύπωση.' } ], storyLabel:'Η ΙΣΤΟΡΙΑ ΜΑΣ', heroTitle:'ΧΤΙΖΟΥΜΕ BRANDS.', statement:'Το BNDL ΕΙΝΑΙ Η ΓΡΗΓΟΡΟΤΕΡΗ ΤΡΟΠΟΣ ΝΑ ΞΕΚΙΝΗΣΕΙΣ ΤΟ BRAND ΣΟΥ.', statementDesc:'Ξεκινήσαμε το BNDL γιατί η δημιουργία ενός brand δεν πρέπει να απαιτεί 10 διαφορετικούς προμηθευτές, 20 emails και 3 μήνες αναμονής. Ένα πακέτο. Όλα όσα χρειάζεσαι. Με την υποστήριξη της Succit wholesale υποδομής.', stat1:'Κατηγορίες Πακέτων', stat2:'Έτοιμα Πακέτα', stat3:'Μέσος Χρόνος Έναρξης Παραγωγής', stat4:'Custom Branded', missionTitle:'Η ΑΠΟΣΤΟΛΗ ΜΑΣ', missionDesc:'Να κάνουμε το custom branding προσιτό και γρήγορο για κάθε επιχείρηση στην Ελλάδα.', succitPretitle:'ΤΟ BNDL ΥΠΟΣΤΗΡΙΖΕΤΑΙ ΑΠΟ', succitDesc:'Η κορυφαία εταιρεία χονδρικής εισαγωγής και customization στην Ελλάδα', succitButton:'Επίσκεψη Succit →', ctaTitle:'Έτοιμος να χτίσεις το brand σου;', ctaPrimary:'Δες τα Πακέτα', ctaSecondary:'Κλείσε Ραντεβού' },
    contact: { title:'Επικοινωνία', subtitle:'Έχεις ερώτηση; Θα χαρούμε να ακούσουμε.', name:'Όνομα', email:'Email', subject:'Θέμα', message:'Μήνυμα', send:'Αποστολή', info:'Στοιχεία Επικοινωνίας', emailLabel:'Email', phoneLabel:'Τηλέφωνο', addressLabel:'Διεύθυνση', addressValue:'Αθήνα, Ελλάδα' },
    faq: { title:'Συχνές Ερωτήσεις', subtitle:'Όλα όσα χρειάζεται να γνωρίζεις για τις παραγγελίες στο BNDL' },
    bookCall: { title:'Κλείσε Ραντεβού', subtitle:'Προγραμμάτισε μια δωρεάν συνεδρία.', desc:'Κατά τη διάρκεια θα συζητήσουμε το brand σου, θα σε βοηθήσουμε να επιλέξεις πακέτο και θα απαντήσουμε σε κάθε ερώτηση.', contact:'Προτιμάς να επικοινωνήσεις απευθείας;' },
    buildOwn: { title:'Φτιάξε το Δικό σου Πακέτο', subtitle:'Δεν βρίσκεις το ιδανικό πακέτο; Πες μας τι χρειάζεσαι.', desc:'Συμπλήρωσε τη φόρμα και θα επικοινωνήσουμε μαζί σου εντός 24 ωρών.', name:'Όνομα', email:'Email', phone:'Τηλέφωνο', company:'Εταιρεία', description:'Περιγραφή', quantity:'Εκτιμώμενη Ποσότητα', budget:'Εύρος Budget', submit:'Υποβολή', success:'Αποστάλθηκε! Θα επικοινωνήσουμε εντός 24 ωρών.' },
    blog: { title:'Blog', subtitle:'Συμβουλές, τάσεις και insights για branded merchandise', readMore:'Διαβάστε Περισσότερα', minRead:'λεπτά' },
    membership: { title:'BNDL Membership', subtitle:'Εξοικονόμησε περισσότερο με κάθε παραγγελία', monthly:'MONTHLY', annual:'ANNUAL ★ BEST VALUE', perMonth:'/μήνα', perYear:'/χρόνο', savings:'(αντί €228 — εξοικονόμηση €79)', feature1:'✓ 5% έκπτωση σε όλα τα bundles', feature2:'✓ Δωρεάν αυτοκόλλητα σε κάθε παραγγελία', feature3:'✓ 1 custom στυλό ανά παραγγελία', feature4:'✓ Συμβουλευτική υποστήριξη (email)', feature5:'✓ Προτεραιότητα στην παραγωγή', feature6:'✓ Συμβουλευτική υποστήριξη (email + τηλέφωνο)', feature7:'✓ 1 δωρεάν sampling ανά έτος', feature8:'✓ Αποκλειστικές προσφορές μελών', getStarted:'Ξεκίνα Τώρα', faqTitle:'Συχνές Ερωτήσεις', faq1:{ question:'Πώς λειτουργεί η έκπτωση 5%;', answer:'Εφαρμόζεται αυτόματα σε κάθε παραγγελία bundle που κάνεις ενώ είσαι μέλος.' }, faq2:{ question:'Πότε χρεώνομαι;', answer:'Αμέσως κατά την εγγραφή και μετά κάθε μήνα/χρόνο αυτόματα.' }, faq3:{ question:'Μπορώ να ακυρώσω;', answer:'Ναι, ανά πάσα στιγμή χωρίς χρεώσεις ακύρωσης.' }, faq4:{ question:'Τα αυτοκόλλητα και το στυλό είναι custom;', answer:'Τα αυτοκόλλητα φέρουν το λογότυπό σου. Το στυλό είναι branded BNDL.' } },
    cookie: { text:'Χρησιμοποιούμε cookies για τη βελτίωση της εμπειρίας σου. Συνεχίζοντας, αποδέχεσαι τη χρήση cookies.', accept:'Αποδοχή' },
    backToTop: 'Επάνω',
  }
};

const FAQ_DATA = [
  { q:'How does ordering work?', qGr:'Πώς λειτουργεί η παραγγελία;', a:'Choose your bundle, complete checkout, then send us your logo. We\'ll send you a proof for approval, produce your order, and ship it to you.', aGr:'Διάλεξε το πακέτο σου, ολοκλήρωσε την αγορά, και στείλε μας το logo σου. Θα σου στείλουμε proof προς έγκριση, θα παράξουμε την παραγγελία και θα στην αποστείλουμε.' },
  { q:'How do I send my logo?', qGr:'Πώς στέλνω το logo μου;', a:'After purchase, you\'ll receive an email with instructions. Send your logo in high-resolution format (AI, EPS, PDF, or PNG at 300dpi minimum).', aGr:'Μετά την αγορά, θα λάβεις email με οδηγίες. Στείλε το logo σε υψηλή ανάλυση (AI, EPS, PDF ή PNG 300dpi minimum).' },
  { q:'What if I don\'t have a logo?', qGr:'Τι γίνεται αν δεν έχω logo;', a:'We offer graphic design services at an additional cost. Contact us for a quote.', aGr:'Προσφέρουμε υπηρεσίες γραφιστικής με επιπλέον κόστος. Επικοινωνήστε μαζί μας για προσφορά.' },
  { q:'What if my design needs adjustments?', qGr:'Τι γίνεται αν το σχέδιό μου χρειάζεται τροποποιήσεις;', a:'If your logo file needs artwork setup or fixing, there\'s a €30 artwork setup fee.', aGr:'Αν το αρχείο logo χρειάζεται προετοιμασία, υπάρχει χρέωση €30 για artwork setup.' },
  { q:'Can I choose sizes?', qGr:'Μπορώ να επιλέξω μεγέθη;', a:'Yes! After purchase, you\'ll select your size breakdown (XS to 2XL) for each item.', aGr:'Ναι! Μετά την αγορά, θα επιλέξεις τα μεγέθη (XS έως 2XL) για κάθε προϊόν.' },
  { q:'Does more colors mean higher cost?', qGr:'Περισσότερα χρώματα σημαίνει μεγαλύτερο κόστος;', a:'Multi-color printing may increase cost depending on the method. Simple 1-2 color designs are included in the bundle price.', aGr:'Η πολύχρωμη εκτύπωση μπορεί να αυξήσει το κόστος. Απλά σχέδια 1-2 χρωμάτων περιλαμβάνονται στην τιμή.' },
  { q:'What printing methods do you use?', qGr:'Τι μεθόδους εκτύπωσης χρησιμοποιείτε;', a:'We offer screen printing, DTG, DTF, embroidery, and vinyl — we\'ll recommend the best method for your design.', aGr:'Προσφέρουμε μεταξοτυπία, DTG, DTF, κέντημα και vinyl — θα σας προτείνουμε τη βέλτιστη μέθοδο.' },
  { q:'Are prices including VAT?', qGr:'Οι τιμές περιλαμβάνουν ΦΠΑ;', a:'All displayed prices exclude 24% VAT. VAT is added at checkout.', aGr:'Όλες οι τιμές δεν περιλαμβάνουν 24% ΦΠΑ. Ο ΦΠΑ προστίθεται στο checkout.' },
  { q:'What about shipping?', qGr:'Τι γίνεται με τα μεταφορικά;', a:'Shipping is calculated separately based on order size. We deliver across Greece via all major courier services.', aGr:'Τα μεταφορικά υπολογίζονται ξεχωριστά. Παράδοση σε όλη την Ελλάδα.' },
  { q:'Can I order a sample first?', qGr:'Μπορώ να αγοράσω δείγμα;', a:'Yes! Sampling is available at an extra cost. Contact us for details.', aGr:'Ναι! Τα δείγματα είναι διαθέσιμα με επιπλέον κόστος.' },
  { q:'What is the production time?', qGr:'Ποιος είναι ο χρόνος παραγωγής;', a:'Typical production time is 10-15 business days after logo approval.', aGr:'Ο τυπικός χρόνος παραγωγής είναι 10-15 εργάσιμες ημέρες μετά την έγκριση logo.' },
  { q:'Can I customize my bundle?', qGr:'Μπορώ να φτιάξω δικό μου πακέτο;', a:'Yes! Check our Custom Bundle category or use the "Build Your Own Bundle" inquiry form.', aGr:'Ναι! Δες το Custom Bundle ή χρησιμοποίησε τη φόρμα "Φτιάξε το Δικό σου".' },
  { q:'Do you ship internationally?', qGr:'Στέλνετε εκτός Ελλάδας;', a:'Currently we ship within Greece only. International shipping coming soon.', aGr:'Αυτή τη στιγμή αποστέλλουμε μόνο εντός Ελλάδας. Διεθνής αποστολή σύντομα.' },
  { q:'Can I get an invoice?', qGr:'Μπορώ να εκδώσω τιμολόγιο;', a:'Yes, invoices are generated automatically. Add your company name and VAT number at checkout.', aGr:'Ναι, τα τιμολόγια εκδίδονται αυτόματα. Πρόσθεσε επωνυμία και ΑΦΜ στο checkout.' },
];

const TESTIMONIALS = [
  { name:'Maria K.', role:'Cafe Owner, Athens', text:'BNDL made our cafe branding so easy. The quality of the aprons and mugs exceeded our expectations!', textGr:'Το BNDL έκανε το branding του καφέ μας πολύ εύκολο. Η ποιότητα ξεπέρασε τις προσδοκίες μας!', stars:5 },
  { name:'Nikos D.', role:'Fitness Studio, Thessaloniki', text:'We ordered the Fitness Classics bundle for our gym. Fast production, great quality, fair price.', textGr:'Παραγγείλαμε το Fitness Classics πακέτο. Γρήγορη παραγωγή, εξαιρετική ποιότητα, δίκαιη τιμή.', stars:5 },
  { name:'Elena S.', role:'Creator & Influencer', text:'As a content creator, having my own merch was a dream. BNDL made it affordable and hassle-free!', textGr:'Τα δικά μου merch ήταν ένα όνειρο. Το BNDL το έκανε προσιτό και χωρίς stress!', stars:5 },
  { name:'Yiannis P.', role:'University Club President', text:'Our fraternity ordered the University Advanced bundle. Everyone loved the hoodies. Will order again!', textGr:'Η αδελφότητά μας παρήγγειλε το University Advanced. Όλοι λάτρεψαν τα hoodies!', stars:5 },
  { name:'Sophia M.', role:'Wedding Planner', text:'The wedding bundles were perfect for our clients. Custom totes and tees added a personal touch.', textGr:'Τα γαμήλια πακέτα ήταν τέλεια. Custom totes και tees πρόσθεσαν προσωπική πινελιά.', stars:5 },
];

const BLOG_POSTS = [
  { slug:'why-branded-merchandise-matters', title:'Why Branded Merchandise Matters for Your Business', titleGr:'Γιατί το Branded Merchandise Έχει Σημασία', excerpt:'Discover how branded merchandise can boost your brand recognition and customer loyalty.', excerptGr:'Ανακαλύψτε πώς το branded merchandise μπορεί να ενισχύσει το brand σας.', date:'2026-03-10', readTime:5, image:'images/pexels-dtanpt-1129019.jpg', content:'Branded merchandise is more than just promotional items — it\'s a powerful marketing tool that creates lasting impressions. When your customers wear your branded tee or carry your tote bag, they become walking advertisements for your business.\n\nStudies show that 85% of consumers remember the advertiser who gave them a branded item. This makes merchandise one of the most effective forms of marketing, with a lower cost-per-impression than digital advertising.\n\nAt BNDL, we make it easy to get started with our fixed-price bundles that include everything you need — from blank products to custom printing with your logo.', contentGr:'Το branded merchandise είναι κάτι περισσότερο από διαφημιστικά αντικείμενα — είναι ένα ισχυρό εργαλείο marketing.' },
  { slug:'choosing-right-bundle', title:'How to Choose the Right Bundle for Your Brand', titleGr:'Πώς να Επιλέξεις το Σωστό Πακέτο', excerpt:'A guide to selecting the perfect BNDL bundle based on your industry and goals.', excerptGr:'Ένας οδηγός για την επιλογή του ιδανικού πακέτου BNDL.', date:'2026-03-05', readTime:4, image:'images/pexels-gabby-k-6311332.jpg', content:'Choosing the right merchandise bundle depends on your industry, target audience, and budget. Here\'s a quick guide to help you decide.\n\nFor retail & clothing brands: Start with the Clothing Brand bundles. These include tees, hoodies, caps, and tote bags — the essentials for any fashion-forward brand.\n\nFor corporate & B2B: Our Corporate bundles include polo shirts, notebooks, and pens — perfect for professional settings and trade shows.\n\nFor events & communities: Music, University, and Sports bundles are designed for large groups with items that create a sense of belonging.', contentGr:'Η επιλογή του σωστού πακέτου εξαρτάται από τον κλάδο, το κοινό-στόχο και τον προϋπολογισμό σου.' },
  { slug:'printing-methods-explained', title:'Printing Methods Explained: Which One Is Right for You?', titleGr:'Μέθοδοι Εκτύπωσης: Ποια Είναι η Κατάλληλη;', excerpt:'Screen printing, DTG, DTF, embroidery — learn the pros and cons of each method.', excerptGr:'Μεταξοτυπία, DTG, DTF, κέντημα — μάθε τα πλεονεκτήματα κάθε μεθόδου.', date:'2026-02-28', readTime:6, image:'images/pexels-ron-lach-9256867.jpg', content:'Understanding printing methods helps you make the best choice for your branded merchandise.\n\nScreen Printing: Best for large orders with 1-3 colors. Durable, vibrant, and cost-effective at scale.\n\nDTG (Direct to Garment): Perfect for detailed, full-color designs. Best for smaller quantities.\n\nDTF (Direct to Film): Versatile and works on any fabric color. Great for photographic-quality prints.\n\nEmbroidery: Premium feel, extremely durable. Ideal for logos on polos, caps, and hoodies.\n\nVinyl: Sharp, clean lines for simple designs. Works great on sportswear.', contentGr:'Η κατανόηση των μεθόδων εκτύπωσης σε βοηθά να κάνεις τη σωστή επιλογή.' },
];

const DISCOUNT_CODES = {
  'WELCOME10': { type:'percent', value:10, label:'10% off' },
  'SAVE20': { type:'fixed', value:20, label:'€20 off' },
  'BNDL15': { type:'percent', value:15, label:'15% off' },
};
